name: ealstm
channels:
  - pytorch
  - conda-forge
  - bokeh
  - anaconda
  - defaults
dependencies:
  - astroid=2.2.5=py37_0
  - attrs=19.1.0=py37_1
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - bokeh=1.2.0=py_0
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.3.9=py37_0
  - cffi=1.12.3=py37h2e261b9_0
  - cftime=1.0.3.4=py37hdd07704_1
  - curl=7.64.1=hbc83047_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - futures-compat=1.0=py3_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=hb3b607b_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py37h7918eee_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.4=243
  - ipykernel=5.1.1=py37h39e3cac_0
  - ipython=7.5.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.4.2=py37_0
  - isort=4.3.20=py37_0
  - jedi=0.13.3=py37_0
  - jinja2=2.10.1=py37_0
  - joblib=0.13.2=py37_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.1=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.4.0=py37_0
  - kiwisolver=1.1.0=py37he6710b0_0
  - krb5=1.16.1=h173b8e3_7
  - lazy-object-proxy=1.4.1=py37h7b6447c_0
  - libcurl=7.64.1=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libnetcdf=4.6.1=h11d0813_2
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.8.2=h1ba5d50_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - llvmlite=0.28.0=py37hd408876_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.0=py37h5429711_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py37h7b6447c_0
  - mkl_fft=1.0.12=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=he6710b0_1
  - netcdf4=1.4.2=py37h808af73_0
  - ninja=1.9.0=py37hfd86e86_0
  - notebook=5.7.8=py37_0
  - numba=0.43.1=py37h962f231_0
  - numpy=1.16.4=py37h7e9f1db_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1b=h14c3975_1
  - packaging=19.0=py37_0
  - pandas=0.24.2=py37he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.4.0=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=6.0.0=py37h34e0f95_0
  - pip=19.1.1=py37_0
  - prometheus_client=0.6.0=py37_0
  - prompt_toolkit=2.0.9=py37_0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.4.2=py_0
  - pylint=2.3.1=py37_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.14.11=py37h7b6447c_0
  - python=3.7.3=h0371630_0
  - python-dateutil=2.8.0=py37_0
  - pytorch-cpu=1.1.0=py3.7_cpu_0
  - pytz=2019.1=py_0
  - pyyaml=5.1=py37h7b6447c_0
  - pyzmq=18.0.0=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.5.1=py_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.21.2=py37hd81dba3_0
  - scipy=1.2.1=py37h7c811a0_0
  - send2trash=1.5.0=py37_0
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.28.0=h7b6447c_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py37_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.2=py37h7b6447c_0
  - tqdm=4.32.1=py_0
  - traitlets=4.3.2=py37_0
  - umap-learn=0.3.9=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.4=py37_0
  - widgetsnbextension=3.4.2=py37_0
  - wrapt=1.11.1=py37h7b6447c_0
  - xarray=0.12.1=py_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - yapf==0.27.0

